// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqmnipz8QdT7gNZQC3KRSn9tF5QL10k1A',
    appId: '1:964107359747:web:c529590acf68c73acbe036',
    messagingSenderId: '964107359747',
    projectId: 'auth-form-3604e',
    authDomain: 'auth-form-3604e.firebaseapp.com',
    storageBucket: 'auth-form-3604e.firebasestorage.app',
    measurementId: 'G-0527390N4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbePAR4s0NrnnjYMgZn4kNFhyskdeHqTE',
    appId: '1:964107359747:android:bbd66542ad8561dccbe036',
    messagingSenderId: '964107359747',
    projectId: 'auth-form-3604e',
    storageBucket: 'auth-form-3604e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbqyAbroOKUNhLch9g0XVeq69ZTR-tet0',
    appId: '1:964107359747:ios:549edf4b92568e51cbe036',
    messagingSenderId: '964107359747',
    projectId: 'auth-form-3604e',
    storageBucket: 'auth-form-3604e.firebasestorage.app',
    iosBundleId: 'com.example.authForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbqyAbroOKUNhLch9g0XVeq69ZTR-tet0',
    appId: '1:964107359747:ios:549edf4b92568e51cbe036',
    messagingSenderId: '964107359747',
    projectId: 'auth-form-3604e',
    storageBucket: 'auth-form-3604e.firebasestorage.app',
    iosBundleId: 'com.example.authForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqmnipz8QdT7gNZQC3KRSn9tF5QL10k1A',
    appId: '1:964107359747:web:96d7ca34fac7f80ccbe036',
    messagingSenderId: '964107359747',
    projectId: 'auth-form-3604e',
    authDomain: 'auth-form-3604e.firebaseapp.com',
    storageBucket: 'auth-form-3604e.firebasestorage.app',
    measurementId: 'G-KB16YMPLZ8',
  );

}